### ISSUE TITLE
any chance to change the license to a more permissive one?

### ISSUE THREAD

**Issue by jhwangbo** [tarik02/machineid#1]
First, thank you for sharing the awesome code! It works out-of-the-box

I guess the purpose of your code is for commercial licensing. Is there any chance of changing the license to zlib, apache, BSD or anything more permissive?

**Comment by tarik02** [comment]
Hello. Thank you for your issue.

I changed the license of the project to Apache License Version 2.0.

Here's the commit: https://github.com/Tarik02/machineid/commit/17b632055943c0c21cb5d8173d07b690dc43383c

**Comment by jhwangbo** [comment]
Great! Thx for the prompt response. Apache2 is awesome!
